# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-11-09 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181109_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body',
            field=models.CharField(default='I am making a blog site to learn django and this is the first post.', max_length=2000),
            preserve_default=False,
        ),
    ]
