# Generated by Django 2.1.3 on 2018-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='rarity',
            field=models.CharField(choices=[('C', 'Common'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary')], default='C', max_length=1),
        ),
    ]
