# Generated by Django 2.1.3 on 2018-11-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_auto_20181115_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='owned_by',
        ),
        migrations.AddField(
            model_name='card',
            name='owned_by',
            field=models.ManyToManyField(to='collector.Collector'),
        ),
    ]
