# Generated by Django 2.1.3 on 2018-11-15 22:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0003_auto_20181115_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='collector',
            name='join_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='join date'),
        ),
    ]
