# Generated by Django 2.1.3 on 2018-11-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0006_auto_20181116_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(default="It's a pile of goo.", max_length=2000),
            preserve_default=False,
        ),
    ]
