# Generated by Django 2.1.3 on 2018-11-16 17:14

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('collector', '0008_auto_20181116_1712'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Copies',
            new_name='CardSet',
        ),
    ]
