# Generated by Django 2.1.3 on 2018-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0009_auto_20181116_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='copies',
            field=models.IntegerField(default=1),
        ),
    ]
